### ISSUE TITLE
503 Service Not Available

### ISSUE THREAD

**Issue by siavashk** [mjedrasz/oauth2-mlflow-aws#1]
I followed the instructions in the repository. The `terraform apply` command finished successfully without any errors. But when I navigated to the `mlflow_uri`, I get the following text rendered: `503 Service Temporarily Unavailable`. How do I fix this?

Please see the atttached screenshot.
![image](https://github.com/mjedrasz/oauth2-mlflow-aws/assets/1020752/8c200727-a2ad-4d76-a3cd-bdb5e0930303)

**Comment by mjedrasz** [comment]
it's a very generic error. Please check the containers' logs - if they are running and are healthy

**Comment by siavashk** [comment]
Thank you. I figured out the issue. It had to do with setting up the oath settings. I think the README would benefit from some clarifications. I will fork the project and submit a PR if you are interested.

**Comment by mjedrasz** [comment]
cool
if something is not clear, please submit a PR. Thanks

**Comment by siavashk** [comment]
I created a pull request here: https://github.com/mjedrasz/oauth2-mlflow-aws/pull/2
